export const characterTypes = {
  LOAD_NEW_CHARACTER: '@@character/LOAD_NEW_CHARACTER',
  LOAD_NEW_CHARACTER_REQUEST: '@@character/LOAD_NEW_CHARACTER_REQUEST',
  LOAD_NEW_CHARACTER_SUCCESS: '@@character/LOAD_NEW_CHARACTER_SUCCESS',
  LOAD_NEW_CHARACTER_ERROR: '@@character/LOAD_NEW_CHARACTER_ERROR',

  CHARACTER_CHANGE_HEALTH: '@@character/CHARACTER_CHANGE_HEALTH',

  CHARACTER_CHANGE_MANA: '@@character/CHARACTER_CHANGE_MANA',

  CHARACTER_CHANGE_EXP: '@@character/CHARACTER_CHANGE_EXP',

  CHARACTER_CHANGE_MONEY: '@@character/CHARACTER_CHANGE_MONEY',
};
